Use MarkupSafe==2.0.1
ImportError: cannot import name 'soft_unicode' from 'markupsafe' is caused by 'soft_unicode' being removed from  MarkupSafe>=2.1.0